//=======================================
//COMPONENT: TaskList
//PURPOSE: Recieves the array of tasks from the TaskBoard 
//and then renders each one as a TaskCard component.
//It also handles the middle of the data flow by recieving the array from above
//and then maps it down into individual TaskCards.
//TYPE: Server Component
//PROPS:
//tasks, array, and the filtered 
// lists of task objects to display.
//=========================================

import TaskCard from './TaskCard';
export default function TaskList({ tasks }) {
  //==EARLY RETURN======================
  //task.length === 0 is used to return a message when the array of tasks are empty.
  //React will not map over an empty array instead it will display
  //nothing on the screen.

  if (tasks.length === 0) {
    return <p className="text-black">No tasks yet!</p>;
  }
  return(
    //==LIST ELEMENT ======================
    //The .map() method is used to loop over the array of tasks and return a new array of TaskCard components with the title and done values passed as props.
    //The key prop is used to help React identify which items have changed, are added, or are removed. It should be a unique identifier for each task, which is why we use the id generated by crypto.randomUUID() in the TaskBoard component.
    <ul className="divide-y">
      {tasks.map((task) => (
        <li key={task.id} >
          <TaskCard title={task.title} done={task.done} />
        </li>
      ))}
    </ul>
      );
    }